GET http://localhost:5000/dashboard

###
GET http://localhost:5000/dashboard/1


###
POST http://localhost:5000/dashboard
Content-Type: application/json

{
    "Provinsi": "Jakarta",
    "SumKelasX": 945678,
    "KelasXPersen": 43.4,
    "SumKelasXI": 24567,
    "KelasXIPersen": 34.4,
    "SumKelasXII": 234578,
    "KelasXIIPersen": 45.2
}
###
POST http://localhost:5000/dashboard
Content-Type: application/json

{
    "Provinsi": "Jakarta",
    "SumKelasX": 945678,
    "KelasXPersen": 43.4,
    "SumKelasXI": 24567,
    "KelasXIPersen": 34.4,
    "SumKelasXII": 234578,
    "KelasXIIPersen": 45.2
}

###
DELETE http://localhost:5000/dashboard/0